### ISSUE TITLE
why are you not using rex-ray?

### ISSUE THREAD

**Issue by AmirAliSobhGol** [flaviostutz/cepher#1]
Hi,

is there a particular reason you chose not to go with [rex-ray](https://github.com/rexray/rexray)?

**Comment by flaviostutz** [comment]
I've been implementing things like distributed READ WRITE volume locks (with TTL) on RBD and cephx key exchange using ETCD along with some specific filesystem administration because I am evaluating if we could replace our existing HDFS by Ceph volumes bound to containers. In this case we need to be laser focused to handle specific performance needs for a great diversity of use cases. To implement these kind of features in a wide solution (that supports dozens of storage providers) - like rex-ray - would require too much effort, so we decided to create a Ceph specialized plugin so that we can evolve it as we experiment with more and more use cases more easily.

Do you have experience with Ceph in Rex-Ray? In which use cases? 

Thanks for the discussion...
